name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==3.0.4
  - pip:
    - sphinx_rtd_theme==1.0.0
sphinx: 
  configuration: docs/source/conf.py
python: 
  install:
     - requirements: docs/requirements.txt
